### ISSUE TITLE
Emotion set

### ISSUE THREAD

**Issue by siddharthkp** [progressive-webapps/emotions#3]
Happy 🙂
Sad 😞
Meh 😕
Angry 😤
Blessed 😊
Dazed 😱

**Comment by hemanth** [comment]
Better we make a sprite out of: 

![](https://d13yacurqjgara.cloudfront.net/users/312280/screenshots/2338760/dribbble.png)

[source](https://dribbble.com/shots/2338760-Emoji-Nucleo)

or use [SVGs](http://git.emojione.com/demos/sprites-svg.html)

**Comment by hemanth** [comment]
We might take an helping hand from @linuxenko if she is interested in this!

**Comment by linuxenko** [comment]
I'd like to help you with it. But only thing i can do is only detect the edges [like this](http://codepen.io/linuxenko/pen/zNOOvX). I cannot name them automatically ))

**Comment by hemanth** [comment]
Cool, it need not be the same, we basically need an emotions sprite 🤗

**Comment by linuxenko** [comment]
Do you mean [simple css sprite](https://gist.github.com/linuxenko/5824294517ccac36aa15ff8ffcac5d55) ?

**Comment by hemanth** [comment]
I feel this should be good to start with? 

An SVG sprite would be more better. 

If you had some time, feel free to modify the `index.html`

**Comment by hemanth** [comment]
Update: pushed some css emojis doesn't look good, I would vote for SVG sprites.

**Comment by linuxenko** [comment]
Something like [this](http://codepen.io/linuxenko/pen/ygBzmd) ?  I mean, emojione does not work as a sprite set of images for svg ([all in one image](https://github.com/Ranks/emojione/blob/master/assets/sprites/emojione.sprites.svg)).

**Comment by hemanth** [comment]
Like the second one but we need to limit it to emotions/feelings.

**Comment by linuxenko** [comment]
Please check out [this pr](https://github.com/progressive-webapps/emotions/pull/6). I think , one image sprite is very bad idea for this because images has a [dynamic](https://github.com/progressive-webapps/emotions/blob/master/style.css#L26) size, i'm not sure is it possible with `onespriteimage` at all.

**Comment by hemanth** [comment]
> one image sprite is very bad idea for this because images has a dynamic size.

True, that was a wrong move. 

PR looks great, I have left few comments over there.

**Comment by hemanth** [comment]
For now this is resolved.
